FROM ubuntu:20.04 

RUN apt update
RUN apt install -y openjdk-17-jdk
RUN apt install -y openjdk-17-jre


COPY target/challenge-0.0.1-SNAPSHOT.jar reto-app.jar
ENTRYPOINT ["java", "-jar", "reto-app.jar"]
