version: "3.9"

services:
  java_db:
    container_name: java_db
    image: mysql:8
    networks:
      - employee-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=retobbva  

  reto_app:
    container_name: reto_app
    image: bbva-reto_app:1.0.0
    ports:
      - "8080:8080"
    networks:
      - employee-mysql
    depends_on:
       - java_db

networks:
  employee-mysql: